server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/gabrielpadilh4/configuration-files-spring-cloud-projeto-microservices-dio.git